spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/book-library-sokol
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: schema.sql
      data-locations: data.sql
      mode: always
server:
  servlet:
    context-path: /book-library